version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '3003:80'
    networks:
      - app-network
  db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '33061:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "yii2basic"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "example"
      TZ: 'Asia/Almaty'
    networks:
      - app-network

      #Docker Networks
networks:
  app-network:
    driver: bridge